#### test code to sample and save indexes

In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter('ignore',DeprecationWarning)

import time
import copy

from pylab import rcParams

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from __future__ import print_function

#### Read in  dataset from .csv file

In [10]:
# ... -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ... read in cleaned data set
# ... -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

data_dir = '../data/'
data_file = 'mashable_clean_dataset_for_lab_03.csv'

file_2_read = data_dir + data_file
df = pd.read_csv(file_2_read)

df.describe().T

,count,mean,std,min,25%,50%,75%,max
n_tokens_title,39644.0,10.398749,2.114037,2.0,9.000000,10.000000,12.000000,23.000000
num_keywords,39644.0,7.223767,1.909130,1.0,6.000000,7.000000,9.000000,10.000000
data_channel_is_lifestyle,39644.0,0.052946,0.223929,0.0,0.000000,0.000000,0.000000,1.000000
data_channel_is_entertainment,39644.0,0.178009,0.382525,0.0,0.000000,0.000000,0.000000,1.000000
data_channel_is_socmed,39644.0,0.058597,0.234871,0.0,0.000000,0.000000,0.000000,1.000000
kw_avg_max,39644.0,1.913205,1.000000,0.0,1.271003,1.800325,2.442234,6.248298
weekday_is_monday,39644.0,0.168020,0.373889,0.0,0.000000,0.000000,0.000000,1.000000
weekday_is_tuesday,39644.0,0.186409,0.389441,0.0,0.000000,0.000000,0.000000,1.000000
weekday_is_wednesday,39644.0,0.187544,0.390353,0.0,0.000000,0.000000,0.000000,1.000000
weekday_is_thursday,39644.0,0.183306,0.386922,0.0,0.000000,0.000000,0.000000,1.000000
weekday_is_friday,39644.0,0.143805,0.350896,0.0,0.000000,0.000000,0.000000,1.000000
is_weekend,39644.0,0.130915,0.337312,0.0,0.000000,0.000000,0.000000,1.000000
global_subjectivity,39644.0,0.443370,0.116685,0.0,0.396167,0.453457,0.508333,1.000000
global_rate_positive_words,39644.0,0.039625,0.017429,0.0,0.028384,0.039023,0.050279,0.155488
rate_positive_words,39644.0,0.682150,0.190206,0.0,0.600000,0.710526,0.800000,1.000000
max_positive_polarity,39644.0,0.756728,0.247786,0.0,0.600000,0.800000,1.000000,1.000000
min_negative_polarity,39644.0,0.478056,0.290290,0.0,0.300000,0.500000,0.700000,1.000000
max_negative_polarity,39644.0,0.892500,0.095373,0.0,0.875000,0.900000,0.950000,1.000000
title_sentiment_polarity,39644.0,1.071425,0.265450,0.0,1.000000,1.000000,1.150000,2.000000
abs_title_subjectivity,39644.0,0.341843,0.188791,0.0,0.166667,0.500000,0.500000,0.500000
ln_n_tokens_content,39644.0,5.889971,1.255442,0.0,5.509388,6.016157,6.575076,9.044876
ln_num_hrefs,39644.0,2.156564,0.809445,0.0,1.609438,2.197225,2.708050,5.720312
ln_num_imgs,39644.0,1.116427,0.973755,0.0,0.693147,0.693147,1.609438,4.859812
ln_num_videos,39644.0,0.400420,0.680486,0.0,0.000000,0.000000,0.693147,4.521789
ln_kw_min_min,39644.0,1.174410,1.733030,0.0,0.000000,0.000000,1.791759,5.937536
ln_kw_avg_min,39644.0,5.302209,1.132463,0.0,4.968076,5.470168,5.883322,10.664991
ln_kw_min_max,39644.0,5.045209,4.521016,0.0,0.000000,7.244942,8.974745,13.645079
ln_kw_avg_avg,39644.0,7.976327,0.489467,0.0,7.776304,7.962442,8.189031,10.682093
ln_self_reference_avg_sharess,39644.0,6.667697,3.280186,0.0,6.889782,7.696667,8.556606,13.645079
ln_LDA_00,39644.0,0.148724,0.194635,0.0,0.024742,0.032842,0.215884,0.655961
ln_LDA_01,39644.0,0.117056,0.164989,0.0,0.024705,0.032801,0.140485,0.655418
ln_LDA_02,39644.0,0.172661,0.207322,0.0,0.028171,0.039224,0.288345,0.652325
ln_LDA_03,39644.0,0.176795,0.216061,0.0,0.028171,0.039221,0.319008,0.655722
ln_LDA_04,39644.0,0.186227,0.212166,0.0,0.028173,0.039920,0.336462,0.656063
ln_global_rate_negative_words,39644.0,0.016419,0.010571,0.0,0.009569,0.015221,0.021506,0.169685
ln_min_positive_polarity,39644.0,0.089255,0.060260,0.0,0.048790,0.095310,0.095310,0.693147
ln_abs_title_sentiment_polarity,39644.0,0.128709,0.173844,0.0,0.000000,0.000000,0.223144,0.693147
ln_shares,39644.0,7.474855,0.930486,0.0,6.852243,7.244228,7.937375,13.645078

In [39]:

X1 = copy.deepcopy(df)
X1 = X1.sample(frac = 0.30)

#X1.describe().T

X1.head()

X1_index = list(X1.index.values)

len(X1_index)

df_new = pd.DataFrame(np.random.randn(len(X1_index), 2), columns = list('xy'))

df_new['sample_index'] = X1_index

df_new.head()

data_dir = '../data/'
data_file = 'sample_test.csv'

file_2_write = data_dir + data_file

df_new.to_csv(file_2_write, index_label = 'smpl_index', index = True)

,n_tokens_title,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_socmed,kw_avg_max,weekday_is_monday,weekday_is_tuesday,weekday_is_wednesday,weekday_is_thursday,...,ln_self_reference_avg_sharess,ln_LDA_00,ln_LDA_01,ln_LDA_02,ln_LDA_03,ln_LDA_04,ln_global_rate_negative_words,ln_min_positive_polarity,ln_abs_title_sentiment_polarity,ln_shares
37904,13,6,0,0,0,4.462596,0,1,0,0,...,0.000000,0.182216,0.032807,0.032790,0.530692,0.032790,0.000000,0.00000,0.000000,7.937375
19809,11,6,0,1,0,2.787959,1,0,0,0,...,8.947069,0.032793,0.546722,0.032791,0.159065,0.032790,0.014926,0.04879,0.000000,8.935904
1191,12,8,0,0,0,0.160264,1,0,0,0,...,6.499286,0.024892,0.024695,0.641581,0.024693,0.024998,0.014042,0.04879,0.182322,8.809863
9310,9,9,0,0,0,0.652058,0,1,0,0,...,7.681407,0.021987,0.021987,0.021984,0.022001,0.647662,0.007210,0.09531,0.000000,7.244228
12953,10,8,0,0,0,2.230283,0,0,0,0,...,0.000000,0.160838,0.024695,0.361449,0.024693,0.292741,0.010336,0.09531,0.000000,6.606650

11893

          x         y  sample_index
0 -0.071295 -0.174986         37904
1  1.412821 -1.116556         19809
2  0.145319  0.976376          1191
3  0.580972 -0.968543          9310
4  0.970737 -0.622176         12953

In [40]:
data_dir = '../data/'
data_file = 'sample_test.csv'

file_2_read = data_dir + data_file
df_xxx = pd.read_csv(file_2_read)

df_xxx.describe().T

df_xxx.head()

,count,mean,std,min,25%,50%,75%,max
smpl_index,11893.0,5946.000000,3433.357710,0.000000,2973.000000,5946.000000,8919.000000,11892.000000
x,11893.0,0.003514,0.993461,-3.491364,-0.666020,0.005866,0.670688,3.647951
y,11893.0,0.010719,1.006123,-3.600557,-0.667038,0.006851,0.681553,3.943785
sample_index,11893.0,19667.501976,11461.462914,2.000000,9717.000000,19536.000000,29638.000000,39643.000000

   smpl_index         x         y  sample_index
0           0 -0.071295 -0.174986         37904
1           1  1.412821 -1.116556         19809
2           2  0.145319  0.976376          1191
3           3  0.580972 -0.968543          9310
4           4  0.970737 -0.622176         12953

In [38]:


df_join = df_xxx.join(df, on = 'sample_index')

df_join.head()

df.ix[13367]

,index,x,y,sample_index,n_tokens_title,num_keywords,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_socmed,kw_avg_max,...,ln_self_reference_avg_sharess,ln_LDA_00,ln_LDA_01,ln_LDA_02,ln_LDA_03,ln_LDA_04,ln_global_rate_negative_words,ln_min_positive_polarity,ln_abs_title_sentiment_polarity,ln_shares
0,0,0.525483,0.721437,13367,11,10,0,0,0,2.613475,...,8.556606,0.178041,0.019813,0.019811,0.350816,0.296305,0.000000,0.095310,0.438255,8.948976
1,1,-0.616143,0.088902,26037,11,4,0,0,0,2.959818,...,7.170888,0.048795,0.048796,0.586939,0.050226,0.048796,0.007624,0.095310,0.223144,7.600902
2,2,-0.617659,0.061480,17161,9,8,0,0,0,2.024869,...,0.000000,0.024704,0.471458,0.024694,0.279642,0.024694,0.000000,0.000000,0.223144,7.003065
3,3,1.224380,0.505546,8007,11,7,0,0,0,2.146918,...,7.711698,0.028171,0.028172,0.528566,0.028171,0.197034,0.021796,0.060625,0.139762,7.600902
4,4,1.410178,1.002125,25580,9,5,0,0,0,3.301778,...,7.811028,0.609763,0.039222,0.039222,0.039221,0.039221,0.008247,0.032790,0.000000,7.649693

n_tokens_title                     11.000000
num_keywords                       10.000000
data_channel_is_lifestyle           0.000000
data_channel_is_entertainment       0.000000
data_channel_is_socmed              0.000000
kw_avg_max                          2.613475
weekday_is_monday                   0.000000
weekday_is_tuesday                  0.000000
weekday_is_wednesday                0.000000
weekday_is_thursday                 0.000000
weekday_is_friday                   0.000000
is_weekend                          1.000000
global_subjectivity                 0.566296
global_rate_positive_words          0.071429
rate_positive_words                 1.000000
max_positive_polarity               0.600000
min_negative_polarity               1.000000
max_negative_polarity               1.000000
title_sentiment_polarity            1.550000
abs_title_subjectivity              0.200000
ln_n_tokens_content                 5.129899
ln_num_hrefs                        1.945910
ln_num_imgs                         0.000000
ln_num_videos                       1.098612
ln_kw_min_min                       1.791759
ln_kw_avg_min                       5.759217
ln_kw_min_max                       8.556606
ln_kw_avg_avg                       8.268522
ln_self_reference_avg_sharess       8.556606
ln_LDA_00                           0.178041
ln_LDA_01                           0.019813
ln_LDA_02                           0.019811
ln_LDA_03                           0.350816
ln_LDA_04                           0.296305
ln_global_rate_negative_words       0.000000
ln_min_positive_polarity            0.095310
ln_abs_title_sentiment_polarity     0.438255
ln_shares                           8.948976
Name: 13367, dtype: float64

<a href='#toc'> Table of Contents</a>

<a name='end_of_file'></a>
<font color="blue" size=3>  end of file